apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hwc
  labels:
    app: hwc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwc
  template:
    metadata:
      labels:
        app: hwc
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - image: smcquay/hwc:v0.0.8
        name: hwc
        ports:
          - containerPort: 8081
        command: ["/bin/hwc"]
        args: ["hw.default.svc.cluster.local"]
      - image: smcquay/alpine:v0.0.2
        name: debug
