apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hw
  labels:
    app: hw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: hw
        image: smcquay/hw:v0.1.2
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 5
      - image: smcquay/alpine:v0.0.5
        name: debug
