apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hwl
  labels:
    app: hwl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwl
  template:
    metadata:
      labels:
        app: hwl
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: hwl
        image: smcquay/hwl:v0.1.2
      - image: smcquay/alpine:v0.0.5
        name: debug
